---
- name: File create, copy
  hosts: localhost
  check_mode: no
  tasks:
   - name: creating a file 
     file:
      path: /home/ansible1/dev/hosts1
      state: touch
- name: copy the file from local to destination
  hosts: monitor
  tasks:
    - name: copy the file
      copy:
       src: /home/ansible1/dev/hosts1
       dest: /tmp
       owner: ansible1
       group: ansible1
