---
- name: dynamic entry of ip address fully qualified name and hostname
  hosts: all
  tasks:
   - name: hostname and ip display,fqdn
     copy: 
      content: |
       {{ansible_default_ipv4.address}} {{ansible_hostname}} {{ansible_fqdn}}
      dest: /opt/hosts

