---
- hosts: webservers
 become: yes
  tasks:
    - name: install Apache server
      yum:
        name: httpd
        state: latest

     - name: enable and start Apache server
       service:
         name: httpd
         enabled: yes
         state: started
     - name: open firewall port
       firewalld:
         service: http
         immediate: true
         permanent: true
         state: enabled

     - name: create web admin group
       group:
         name: web
         state: present
      - name: create web admin user
           user:
                  name: webadm
                         comment: "Web Admin"
                                password: $6$rounds=656000$bp7zTIl.nar2WQPS$U5CBB15GHnzBqnhY0r7UX65FrBI6w/w9YcAL2kN9PpDaYQIDY6Bi.CAEL6PRRKUqe2bJYgsayyh9NOP1kUy4w.
                                       groups: web
                                              append: yes

