---
- name: creating a user devops with password
  hosts: monitor
  tasks: 
  - name: creating user
    user:
     name: devops
     password: redhat
- name: create a file
  file:
   path: /home/devops/devops.yaml
   state: touch
- name: copying  a file and printing helloworld
  hosts: monitor
  tasks:
   - name: create helloworld file
     copy:
      src: /home/devops/devops.yaml
      dest: /tmp
     content: |
     printing helloworld
     remote_src: yes


