---
- name: copy the content to destination 
  hosts: monitor
  #vars:
   #- localvar: /home/ansible1/localvariable
   #- optvar: /opt/localvariable
   #- path1: /opt
  tasks:
   - name: creating a directory
     file: 
      path: "{{ dirpath }}"
      state: directory
   - name: creating group
     group: 
      name: monitor
      state: present
   - name: creating a file
     file: 
      path: "{{ localvar }}"
      state: touch
      owner: ansible
   - name: copy it to the destination /opt
     copy:
      src:  "{{ localvar }}"
      dest: "{{ path1 }}"
      remote_src: yes
  



   
