---
- name: install httpd
  yum: name=httpd state=latest
- name: start httpd service
  service: name=httpd state=restarted enabled=yes
- name: copy the html file
  copy:
   src: html/
   dest: "/var/www/vhosts/{{ ansible_hostname }}"
- name: vhost template file
  template:
   src: vhost.conf.j2
   dest: /etc/httpd/conf.d/vhost.conf
   owner: root
   group: root
   mode: 0644
  notify:
    - restart httpd


